### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by DennisDavari** [colinzhaoust/reference-free_TS_evaluation#1]
For some pairs of input and output sentences I get the following error: `ValueError: max() arg is an empty sequence`. In the error message it is written that line 171 in metric.py (`simp_score =  max(p_simp)`) causes the error message. Interestingly, for some pairs of input and output sentences the code executes just fine. This is my code which I am running in a new Python file:

```
from metric import r_meaning_score, `p_simp_score
from comparative_complexity import *

# setup
tokenizer = BertTokenizer.from_pretrained(r'./bert-base-uncased')
lm_model = BertModel.from_pretrained(r'./bert-base-uncased')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
lm_model.to(device)
ranker = torch.load(r"./bert_base_all.ckpt", map_location=torch.device('cpu'))
ranker.to(device)

# Compute r_meaning_score
r_mean_score = r_meaning_score(input_sent, output_sent, tokenizer, lm_model, device)
print(f"R Meaning Score: {r_mean_score}")

# Compute p_simp_score
p_simp_score_value = p_simp_score(input_sent, output_sent, tokenizer, lm_model, ranker, device)
print(f"P Simp Score: {p_simp_score_value}")
```

When running the code for `input_sent = "He is sophisticated."` and `output_sent = "He is smart."` the code works just fine. I get an R meaning preservation score of 0.9413632035255433 and a P simplification score of -0.055137112736701965. However, when I run the code with `input_sent = "one"` and `output_sent = "one"` I get a P meaning preservation score of 1.0 and the ValueError instead of the P simplification score.

I didn't really understand the code provided under the **Usage**  section which is why I just sticked to the r_meaning_score and p_simp_score functions from metric.py.

**Comment by colinzhaoust** [comment]
this is actually not a bug. The code basically works on sentence pairs with unique words that form potential simplicity change. To solve this issue, you can check line 131 of metric.py: for uwd in unique_words. You can either choose a pair of inputs with unique words, e.g., "one" vs. "1" or change the code to traverse all words instead of just unique words

**Comment by DennisDavari** [comment]
All right, this makes sense! What I just did now as an adjustment is that I return a simp score of 0 if both sentences have the same set of unique words.

**Comment by colinzhaoust** [comment]
you solution also makes sense.
